---
title: "California wines and climate literature review"
output: html_document
---

### Modeling climate change impacts on wine grape yields and quality in California (Cahill et al. 2007)

#### Summary

* Projections of wine quality in varying climate regions were modeled based on potential climate future scenarios
    * These included multiple emission scenarios, climate models, multiple statistical yield models

* Conclusion: Climate changes will be bad for much of California's viticulture

#### Model predictors

What were the environmental parameters that were strong predictors?
* Nighttime temperatures in April (during Flowering)
* June precipitation
* Precipitation in October preceding harvest 

* Important to remember that grape yields are highly manipulated by viticulturists

#### Variable production types by region

Two major modes of production for California wines:
1. Great Central Valley - Climate is warmer; larger-scale production 
2. Coastal regions - Usually cooler; smaller-scale production

#### Future quality projections

* Predicted temperatures were used to estimate grape ripening time based on **accumulated growing degree days (GDD)** and **average monthly temperature at the GDD derived ripening month**.

What's a growing degree day (GDD)?
* According to [https://mrcc.illinois.edu/gismaps/info/gddinfo.htm](this source), GDDs are used to estimate the growth and development of plants during the growing season
* Development will only occur is a minimum temperature threshold is exceeded (called TBASE). * TBASE is determined experimentally. Cahill et al. 2007 estimates TBASE to be 10 &deg;C. 

To calculate:
* Find mean daily temperature: (high-low)/2
* If TMEAN <= TBASE, then GDD = 0
* If TMEAN >= TBASE, then GDD = TMEAN - TBASE

* According to Amerine and Winkler 1944, grape ripening requires between 1150-1300 GDD above the threshold of 10 &deg;C from April to October 

#### Environmental data and yields

* Yield data collecetd from the California country agricultural commissioners
* Historcal climate data collected from 382 cooperative weather stations throughout California 
    * Used to generate monthly time series for the average daily minimum and maximum temperatures and precipitation
* Regressions were used to identify key climate variables and periods that explained anomalies in wine grape yields

### Asymmetric warming over coastal California and its impact on the premium wine industry

@nemani2001

**Introduction**

* Ocean and land temperatures tend to covary in coastal regions of western North America
    * Caused by the horizontal transport of water vapor

* Increased water vapor results in increased dewpoint temperatures that raise minimum temperatures along the coast.
    * Higher minimum temperatures mean fewer frost events and a longer-frost free growing season length
    
* Why are grapes responsive to long-term changes in climate?
    * The winegrape, *Vitis vinifera*, is a long-lived species (>50 years) is that is less fertilized and less irrigated than other agricultural crops.

* What environmental variables are associated with high quality wines?
    * Low frost damage in mild winters (Considered to be January, February, and March)
    * Early and even budburst, flowering, and development during warm springs (April, May, June)
    * Optimal maturation with low summer temperature variability (July, August, September)
    
**Methods**

* Climate data included SST, sea-level pressure (SLP), and specific humidity (*q*)
    * Time series of SST was developed for a 5&deg; x 5&deg; section of ocean off of central CA

* Lower SLP in the Pacific, and in particular during the winter, brings stronger winds blowing into CA. 
  * Winters with low SLPs tend to also bring warmer temperatures to CA
  
* Covariability between Pacific SSTs and coastal CA temps was tested by averaging air temperatures in the north, central, and south coastal areas (data from NCDC)

* Daily dewpoint temperatures (T<sub>dew</sub>) were taken from San Diego and San Francisco airports
* Cloud cover was also collected at these airports

* Study areas were **Napa and Sonoma Valleys (NSV)**

* Some important biophysical variables were estimated for viticulture
    * Frost frequency
        * The number of days in a year with T<sub>min</sub> < 0&deg;C
    * Growing Degree Days (GDD)
        * Accumulated heat units above a base temperature
    * Vapor Pressure Deficits
        * Difference in vapor pressures at T<sub>dew</sub> and T<sub>max</sub> during the growing season
    * Growing season length
        * Date of winegrape flowering was estimated 

